<?php 
/**
	Admin Page Framework v3.8.34 by Michael Uno 
	Generated by PHP Class Files Script Generator <https://github.com/michaeluno/PHP-Class-Files-Script-Generator>
	<http://en.michaeluno.jp/dgenny>
	Copyright (c) 2013-2021, Michael Uno; Licensed under MIT <http://opensource.org/licenses/MIT> */
class AdminPageFramework_Form_View___CSS_term_meta extends AdminPageFramework_Form_View___CSS_Base {
    protected function _get() {
        return $this->_getRules();
    }
    private function _getRules() {
        return ".dgenny-form-table-outer-row-term_meta,.dgenny-form-table-outer-row-term_meta > td {margin: 0;padding: 0;}.dgenny-form-table-term_meta > tbody > tr > td {margin-left: 0;padding-left: 0;}.dgenny-form-table-term_meta .dgenny-sectionset,.dgenny-form-table-term_meta .dgenny-section {margin-bottom: 0;}.dgenny-form-table-term_meta.add-new-term .title-colon {margin-left: 0.2em;}.dgenny-form-table-term_meta.add-new-term .dgenny-section .form-table > tbody > tr > td,.dgenny-form-table-term_meta.add-new-term .dgenny-section .form-table > tbody > tr > th{display: inline-block;width: 100%;padding: 0;float: right;clear: right;}.dgenny-form-table-term_meta.add-new-term .dgenny-field {width: auto;}.dgenny-form-table-term_meta.add-new-term .dgenny-field {max-width: 100%;}.dgenny-form-table-term_meta.add-new-term .sortable .dgenny-field {width: auto;} .dgenny-form-table-term_meta.add-new-term .dgenny-section .form-table > tbody > tr > th {font-size: 13px;line-height: 1.5;margin: 0;font-weight: 700;}.dgenny-form-table-term_meta .dgenny-section-title h3 {border: none;font-weight: bold;font-size: 1.12em;margin: 0;padding: 0;font-family: 'Open Sans', sans-serif; cursor: inherit; -webkit-user-select: inherit;-moz-user-select: inherit;user-select: inherit;}.dgenny-form-table-term_meta .dgenny-collapsible-title h3 {margin: 0;}.dgenny-form-table-term_meta h4 {margin: 1em 0;font-size: 1.04em;}.dgenny-form-table-term_meta .dgenny-section-tab h4 {margin: 0;} ";
    }
    }
    